[default]
debug = true
db = {host='localhost', port=5432, user='eric', database='kbase'}

[development]
db = {min_size=2, max_size=5, dynaconf_merge=true}

[staging]
value = 'value for staging'

[testing]
db = {min_size=2, max_size=5, dynaconf_merge=true}

[production]
debug = false

[global]
value = 'value for global'
