CREATE TABLE organization (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT CHECK(LENGTH(name)<=32) NOT NULL UNIQUE
);
COMMENT ON TABLE organization IS '组织';
COMMENT ON COLUMN organization.name IS '名称：组织不能重名';


CREATE TABLE operator (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    organization_id INT NOT NULL REFERENCES organization,
    name TEXT CHECK(LENGTH(name)<=32) NOT NULL,
    mobile TEXT CHECK(LENGTH(mobile)=11) NOT NULL,
    password TEXT,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL,

    EXCLUDE (organization_id WITH =, mobile WITH =) WHERE (active)
);
COMMENT ON TABLE operator IS '操作员';
COMMENT ON COLUMN operator.organization_id IS '所属组织ID';
COMMENT ON COLUMN operator.name IS '姓名';
COMMENT ON COLUMN operator.mobile IS '手机号：一个组织内有效的操作员手机号唯一';
COMMENT ON COLUMN operator.password IS '密码：不可逆加密存储';
COMMENT ON COLUMN operator.is_admin IS '是否是组织管理员';
COMMENT ON COLUMN operator.active IS '是否有效：失效的操作员账号不可用';


CREATE TABLE knowledge_base (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    organization_id INT NOT NULL REFERENCES organization,
    name TEXT CHECK(LENGTH(name)<=32) NOT NULL,
    target_audience SMALLINT NOT NULL,

    UNIQUE (organization_id, name)
);
COMMENT ON TABLE knowledge_base IS '知识库';
COMMENT ON COLUMN knowledge_base.organization_id IS '所属组织ID';
COMMENT ON COLUMN knowledge_base.name IS '名称：一个组织内知识库不能重名';
COMMENT ON COLUMN knowledge_base.target_audience IS '目标受众：1-员工、2-顾客、3-通用';


CREATE TABLE knowledge (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    knowledge_base_id INT NOT NULL REFERENCES knowledge_base,
    question TEXT CHECK(LENGTH(question)<=128) NOT NULL,
    answer_type SMALLINT NOT NULL,
    answer_content JSONB NOT NULL,
    keywords TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[]
);
CREATE INDEX knowledge_keywords_idx ON knowledge USING GIN (keywords);
COMMENT ON TABLE knowledge IS '知识';
COMMENT ON COLUMN knowledge.knowledge_base_id IS '所属知识库';
COMMENT ON COLUMN knowledge.question IS '问题';
COMMENT ON COLUMN knowledge.answer_type IS '答复类型：1-文本、2-图片、3-图文、4-语音、5-视频';
COMMENT ON COLUMN knowledge.answer_content IS '答复内容：不同类型对应的JSON格式参考“微信公众平台技术文档|消息管理|被动回复用户消息”';
COMMENT ON COLUMN knowledge.keywords IS '关键词列表：没有关键词时列表为空';


CREATE TABLE channel (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    organization_id INT NOT NULL REFERENCES organization,
    name TEXT CHECK(LENGTH(name)<=32) NOT NULL UNIQUE,

    UNIQUE (organization_id, name)
);
COMMENT ON TABLE channel IS '渠道';
COMMENT ON COLUMN channel.organization_id IS '所属组织ID';
COMMENT ON COLUMN channel.name IS '名称：一个组织内渠道不能重名';


CREATE TABLE channel_knowledge_base (
    channel_id INT NOT NULL REFERENCES channel,
    knowledge_base_id INT NOT NULL REFERENCES knowledge_base,

    PRIMARY KEY (channel_id, knowledge_base_id)
);
COMMENT ON TABLE channel_knowledge_base IS '渠道知识库：即这个渠道基于这些知识库提供问答服务';


-- 可以尝试TimescaleDB插件优化时序数据存取 发起问询、
CREATE TABLE channel_event (
    channel_id INT NOT NULL REFERENCES channel,
    inquirer_id TEXT NOT NULL,
    type SMALLINT NOT NULL,
    detail JSONB,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX channel_event_occurred_at_idx ON channel_event (occurred_at);
COMMENT ON TABLE channel_event IS '渠道事件：记录渠道问答服务中的事件';
COMMENT ON COLUMN channel_event.channel_id IS '渠道ID';
COMMENT ON COLUMN channel_event.inquirer_id IS '问询人ID';
COMMENT ON COLUMN channel_event.type IS '事件类型：1-问询事件、2-知识选择事件、2-知识放弃事件';
COMMENT ON COLUMN channel_event.detail IS '事件详情';
COMMENT ON COLUMN channel_event.occurred_at IS '发生时间';
